[tool.bumpversion]
current_version = "0.1.1"
parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
"""
serialize = ["{major}.{minor}.{patch}"]
tag = true
sign_tags = true
tag_name = "v{new_version}"
tag_message = "bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "chore(release): Bump version: {current_version} → {new_version}"
commit_args = "--no-verify"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
